version: "3.8"

services:
  postgres:
    container_name: postgres
    build:
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    ports:
      - 5435:5432
    networks:
      - app_network
    restart: always

  app:
    container_name: app
    build:
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - 8080:8080
    networks:
      - app_network
    depends_on:
      - postgres
    restart: always

networks:
  app_network:
    driver: bridge
