apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: postgres
      image: localhost/postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "root1234"
        - name: POSTGRES_USER
          value: "postgres"
    - name: app
      image: localhost/app
      ports:
        - containerPort: 8080
          hostPort: 8080
