version: '3'

tasks:
  run:
    cmds:
      - go run cmd/app/main.go

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./...

  test-cover:
    cmds:
    - touch coverage.out
    - defer: rm coverage.out
    - go test ./... -coverprofile='coverage.out'
    - cat coverage.out | grep -v 'mock' | grep -v 'proto' > coverage_cleaned.out
    - defer: rm coverage_cleaned.out
    - go tool cover -func='coverage_cleaned.out'
